/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoesShop.Views;

import java.util.LinkedList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import shoesShop.DB.Product;
import shoesShop.DB.ProductModel;

/**
 *
 * @author Iryna Butenko
 */
public class CreateCheqRowFrame extends javax.swing.JFrame {

	private String [] models;
	private String [] colors;
	private Integer [] sizes;
	protected ChequeForm parent;
	
    /**
     * Creates new form CreateCheqRowFrame
     */
    public CreateCheqRowFrame() {
    	LinkedList<ProductModel> p = ProductModel.getAllOnStock();
    	models = new String [p.size()];
    	for(int i=0; i<p.size(); i++) {
    		models[i] = p.get(i).getN_model();
    	}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modNum = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        colMod = new javax.swing.JComboBox<>();
        sizeMode = new javax.swing.JComboBox<>();
        numMod = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        addToCheqBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel1.setText("Оберіть модель:");

        modNum.setModel(new DefaultComboBoxModel(models));
        modNum.setSelectedIndex(-1);
        modNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel2.setText("Колір:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel3.setText("Розмір:");

        colMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        colMod.setSelectedIndex(-1);
        colMod.setEnabled(false);
        colMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colModActionPerformed(evt);
            }
        });

        sizeMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sizeMode.setSelectedIndex(-1);
        sizeMode.setEnabled(false);
        sizeMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeModeActionPerformed(evt);
            }
        });

        numMod.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel4.setText("К-сть:");

        addToCheqBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        addToCheqBtn.setText("Додати");
        addToCheqBtn.setEnabled(false);
        addToCheqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCheqBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 10)); // NOI18N
        backBtn.setText("Назад");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Додання товару до чеку");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modNum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colMod, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sizeMode, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numMod)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(addToCheqBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addToCheqBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modNumActionPerformed
       if(modNum.getSelectedIndex()!=-1){
    	   LinkedList<String> c =Product.getAllColorsOfModelInStock((String)modNum.getSelectedItem());
    	   colors = new String[c.size()];
    	   colors = c.toArray(colors);
    	   colMod.setModel(new DefaultComboBoxModel(colors));
           colMod.setEnabled(true);
       }
       else colMod.setEnabled(false);
       colMod.setSelectedIndex(-1);
       sizeMode.setSelectedIndex(-1);
      
    }//GEN-LAST:event_modNumActionPerformed

    private void colModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colModActionPerformed
        if(colMod.getSelectedIndex()!=-1){
           LinkedList<Integer> c = Product.getAllSizesOfModelInStock((String)modNum.getSelectedItem(), (String)colMod.getSelectedItem());
      	   sizes = new Integer[c.size()];
      	   sizes = c.toArray(sizes);
      	   sizeMode.setModel(new DefaultComboBoxModel(sizes));
           sizeMode.setEnabled(true);
       }
        else sizeMode.setEnabled(false);
        sizeMode.setSelectedIndex(-1);
    }//GEN-LAST:event_colModActionPerformed

    private void sizeModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeModeActionPerformed
     if(sizeMode.getSelectedIndex()!=-1){
           numMod.setEnabled(true);
           addToCheqBtn.setEnabled(true);
       }
     else{
        numMod.setEnabled(false);
        addToCheqBtn.setEnabled(false);
     }
    }//GEN-LAST:event_sizeModeActionPerformed

    private void addToCheqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCheqBtnActionPerformed
    	String n_model = (String) modNum.getSelectedItem();
    	String color = (String) colMod.getSelectedItem();
    	int size = (int) sizeMode.getSelectedItem();
    	int n = (int)numMod.getValue();
        if(n>0) {
          if(Product.get(n_model, color, size).getNumber()<n) {
        	  JOptionPane.showMessageDialog(this, 
	      			  "Недостатня кількість на складі", "Помилка", JOptionPane.ERROR_MESSAGE);
          } else {
        	parent.addRowToTable(n_model, color, size, (int) numMod.getValue());
        	this.dispose();
          }
        } else {
        	JOptionPane.showMessageDialog(this, 
	      			  "Неправильно введені параметри", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addToCheqBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCheqRowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCheqRowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCheqRowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCheqRowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCheqRowFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCheqBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> colMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> modNum;
    private javax.swing.JSpinner numMod;
    private javax.swing.JComboBox<String> sizeMode;
    // End of variables declaration//GEN-END:variables
}
