/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoesShop.Views;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.LinkedList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import shoesShop.DB.Cheque;
import shoesShop.DB.ProductModel;
import shoesShop.DB.Seller;

/**
 *
 * @author Iryna Butenko
 */
public class ShopStatFrame extends javax.swing.JFrame {

	private Integer [] sellerss;
	private double total_sum;
	private int tot_n;
    /**
     * Creates new form ShopStatFrame
     */
    public ShopStatFrame() {
    	LinkedList<Seller> s = Seller.getAll();
    	sellerss = new Integer[s.size()+1];
    	for(int i=0; i<s.size(); i++) {
    		sellerss[i] = s.get(i).getNum();
    	}
    
        initComponents();
        sellers.setSelectedIndex(s.size());
        fillTable(Cheque.getAll());
//        from.setDate(new Date());
//        to.setDate(new Date());
    }
    
    private void fillTable(LinkedList<Cheque> l) {
    	
    	 jTable1.setModel(new javax.swing.table.DefaultTableModel(
    	            new Object [][] {

    	            },
    	            new String [] {
    	                "Номер чеку", "Сума", "Продавець", "Дата"
    	            }
    	        ) {
    	            Class[] types = new Class [] {
    	                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
    	            };
    	            boolean[] canEdit = new boolean [] {
    	                false, false, false, false
    	            };

    	            public Class getColumnClass(int columnIndex) {
    	                return types [columnIndex];
    	            }

    	            public boolean isCellEditable(int rowIndex, int columnIndex) {
    	                return canEdit [columnIndex];
    	            }
    	        });
    	
    	Cheque cur;
    	total_sum = 0;
    	tot_n = 0;
    	for(int i =0; i<l.size(); i++) {
    		cur = l.get(i);
    		((DefaultTableModel) jTable1.getModel()).addRow(new Object[]{cur.getN_cheque(),cur.getTotal_sum(), cur.getN_employee(), 
    				cur.getDate()});
    		total_sum += cur.getTotal_sum();
    		tot_n +=cur.getNumOfPair();
    		
    	}
    	sum.setText(total_sum+"");
    	num.setText(tot_n+"");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        to = new org.jdesktop.swingx.JXDatePicker();
        from = new org.jdesktop.swingx.JXDatePicker();
        showStatisticsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        allTime = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sum = new javax.swing.JLabel();
        sellers = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        num = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Номер чеку", "Сума", "Продавець", "Дата"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        backBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 10)); // NOI18N
        backBtn.setText("Назад");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        showStatisticsBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 10)); // NOI18N
        showStatisticsBtn.setText("Чеки за період");
        showStatisticsBtn.setToolTipText("");
        showStatisticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStatisticsBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Загальна сума проданих товарів");

        allTime.setText("вивести чеки за весь час");
        allTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTimeActionPerformed(evt);
            }
        });

        jLabel2.setText("з");

        jLabel3.setText("по");

        sum.setText("0");

        sellers.setModel(new DefaultComboBoxModel(sellerss));
        sellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellersActionPerformed(evt);
            }
        });

        jLabel5.setText("Вивести чеки продавця");

        jLabel6.setText("Загальна кількість проданих товарів");

        num.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(allTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showStatisticsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(sellers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(from, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(to, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allTime)
                        .addGap(22, 22, 22)
                        .addComponent(showStatisticsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(sum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(num))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        HeadMainScreen mainScr=new HeadMainScreen();
    }//GEN-LAST:event_backBtnActionPerformed

    private void allTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTimeActionPerformed
        if(sellers.getSelectedIndex()==sellerss.length-1 || sellers.getSelectedIndex()==-1) {
        	fillTable(Cheque.getAll());
        } else {
        	fillTable(Cheque.getAllBySeller((int) sellers.getSelectedItem()));
        }
        to = new org.jdesktop.swingx.JXDatePicker();
        from = new org.jdesktop.swingx.JXDatePicker();
    }//GEN-LAST:event_allTimeActionPerformed

    private void showStatisticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatisticsBtnActionPerformed
    	if(from.getDate()!=null && to.getDate()!=null) {
	    	LocalDate f = from.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
	        LocalDate t = to.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
	    
	        if(f.isEqual(t) || f.isBefore(t)) {
	        	 if(sellers.getSelectedIndex()==sellerss.length-1 || sellers.getSelectedIndex()==-1) {
	             	fillTable(Cheque.getPeriod(f, t));
	             } else {
	             	fillTable(Cheque.getPeriod(f, t, (int) sellers.getSelectedItem() ));
	             }
	        } else {
	        	JOptionPane.showMessageDialog(this, 
		      			  "Неправильно введена дата.", "Помилка", JOptionPane.ERROR_MESSAGE);
	        }
    	}else {
        	JOptionPane.showMessageDialog(this, 
	      			  "Неправильно введена дата.", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_showStatisticsBtnActionPerformed

    private void sellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellersActionPerformed

    	if(from.getDate()!=null && to.getDate()!=null) {
    		LocalDate f = from.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate t = to.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
            if(f.isEqual(t) || f.isBefore(t)) {
            	 if(sellers.getSelectedIndex()==sellerss.length-1 || sellers.getSelectedIndex()==-1) {
                 	fillTable(Cheque.getPeriod(f, t));
                 } else {
                 	fillTable(Cheque.getPeriod(f, t, (int) sellers.getSelectedItem() ));
                 }
            } else {
            	JOptionPane.showMessageDialog(this, 
    	      			  "Неправильно введена дата.", "Помилка", JOptionPane.ERROR_MESSAGE);
            }
    	} else {
    		if(sellers.getSelectedIndex()==sellerss.length-1 || sellers.getSelectedIndex()==-1) {
            	fillTable(Cheque.getAll());
            } else {
            	fillTable(Cheque.getAllBySeller((int) sellers.getSelectedItem()));
            }
    	}
    }//GEN-LAST:event_sellersActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopStatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopStatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopStatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopStatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopStatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allTime;
    private javax.swing.JButton backBtn;
    private org.jdesktop.swingx.JXDatePicker from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel num;
    private javax.swing.JComboBox<String> sellers;
    private javax.swing.JButton showStatisticsBtn;
    private javax.swing.JLabel sum;
    private org.jdesktop.swingx.JXDatePicker to;
    // End of variables declaration//GEN-END:variables
}
